sudo: required
matrix:
  include:
  - name: "Go 1.11"
    env: TEST_TARGET=go-111
services:
  - docker
before_install:
  - docker-compose build ${TEST_TARGET}
  - docker-compose up -d
install:
before_script:
script:
  - docker-compose exec make test
after_script:
notifications:
