version: '3'
services:
  moto_server:
    build:
      context: ./tests
      dockerfile: Dockerfile.moto_server
    container_name: moto-server
    command: ["moto_server", "ec2", "-H", "0.0.0.0", "-p", "5000"]
    ports:
      - "5000:5000"
    networks:
      amictrl_test_net:
        ipv4_address: 192.168.0.100
  amictrl_local:
    build: &amictrl_build
      context: ./
      dockerfile: ./tests/Dockerfile.golang
    container_name: amictrl-local
    volumes:
      - .:/go/src/amiCtrl
    working_dir: /go/src/amiCtrl
    command: tail -f /dev/null
    networks:
      amictrl_test_net:
        ipv4_address: 192.168.0.2
  amictrl_circleci:
    build: <<: *amictrl_build
    container_name: amictrl-circleci
    working_dir: /go/src/amiCtrl
    networks:
      amictrl_test_net:
        ipv4_address: 192.168.0.3

networks:
  amictrl_test_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.0.0/24